### ISSUE TITLE
Standardize Output Names and delineation of fields

### ISSUE THREAD

**Issue by AlexanderFuentes** [McGillX/edx_data_research#15]
Low priority but we should standardize the names of the reports generated. 

suggest "-" between fields and "_" within fields

course-report_name-addition_information_such_as_problem_id-additional_information_such_as_module_name etc.

**Comment by ueg1990** [comment]
how will we differentiate btw the two?

**Comment by AlexanderFuentes** [comment]
huh differentiate between what?

so the output for a problem_id example would be

(collection)-(script used/command)-problem_id-
body101x-problem-######-Activity_1.csv

**Comment by AlexanderFuentes** [comment]
user_info script would do something like body101x-user_info.csv

**Comment by AlexanderFuentes** [comment]
its kindoff already like that just a bit inconsistant

**Comment by ueg1990** [comment]
made a first attempt on it...let me know if there are any bugs or changes in requirements
