### ISSUE TITLE
Problem_id script needs to take the longest set of sub-problem_ids

### ISSUE THREAD

**Issue by AlexanderFuentes** [McGillX/edx_data_research#16]
If you run 
i4x://McGillX/Body101x/problem/4bee93786b4f40fe947166754203a6b2

you'll see that the output csv is miss aligned + missing a question heading. I'm not sure why missing a question heading would result in miss alignment. 

The first user doesnt have "i4x-McGillX-Body101x-problem-4bee93786b4f40fe947166754203a6b2_10_1" : {} in there input state. My guess is that for this problem_id the question was changed after the first person answered.

**Comment by ueg1990** [comment]
done
