### ISSUE TITLE
Order Problem_id Output

### ISSUE THREAD

**Issue by AlexanderFuentes** [McGillX/edx_data_research#17]
have the sub problem ids arranged in ascending order

i4x-McGillX-Body101x-problem-4bee93786b4f40fe947166754203a6b2_2_1 , i4x-McGillX-Body101x-problem-4bee93786b4f40fe947166754203a6b2_3_1, i4x-McGillX-Body101x-problem-4bee93786b4f40fe947166754203a6b2_4_1

etc.

**Comment by AlexanderFuentes** [comment]
Do you think you can add this in?

**Comment by ueg1990** [comment]
hey Alex, in my code i had ensured that the sub-problem ids were sorted. there is a case where it may fail but can you let me know where did you the sub-problem ids not being ordered?

**Comment by ueg1990** [comment]
done...with a very nice short solution :)

**Comment by AlexanderFuentes** [comment]
K so bug instead of enhancement it was with the same problem ID that was
causing the other issue
