### ISSUE TITLE
display_name prompt

### ISSUE THREAD

**Issue by AlexanderFuentes** [McGillX/edx_data_research#18]
if the display name field is blank have the command line prompt the user to provide a substitute name for the display name

**Comment by AlexanderFuentes** [comment]
Or better yet add custom display name as an optional input parameter

**Comment by AlexanderFuentes** [comment]
yah sorry my message was unclear i think the default value should be "display_name"

**Comment by ueg1990** [comment]
can we close this?

**Comment by AlexanderFuentes** [comment]
yep

On Wed, Sep 2, 2015 at 6:28 PM, Usman Ehtesham Gul <notifications@github.com
> wrote:

> can we close this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/McGillX/edx_data_research/issues/18#issuecomment-137263086>
> .
>



-- 

*Alexander Steeves-Fuentes* | Courseware Developer | McGillX

*Teaching and Learning Services* | McGill University | McLennan Library
Building, MS-12 | 3459 McTavish Street | Montreal, Quebec | H3A 0C8 |
http://www.mcgill.ca/tls
