### ISSUE TITLE
Add ip to country report generation to CLI 

### ISSUE THREAD

**Issue by ueg1990** [McGillX/edx_data_research#27]

**Comment by ueg1990** [comment]
Update: yesterday i worked on integrating the hash ids and anonymize options for forum, course-completers and ip-to-country. The first two had no issues. But ip-to-country has a couple of issues:
1) there are alot of edge cases on the type of the username provided. Apart from a string it can be a number, a long number or a string can be converted into a number....trying to figure that out
2) Tracking collection has number of documents in the millions and number of documents in user_id_map is equal to the number of students (5000-30000). So anonymizing ip-to-country is going to take a long long time IF i use user_id_map to find the user_id and hash_id of given username from the tracking document. Alternate solution is to do the steps sequentially. First i generate an intermediate result from the tracking logs part and then I use the intermediate result to anonymize it and finally generate the report

**Comment by AlexanderFuentes** [comment]
1) "edge cases" ?

2) intermediate seems like the best approach

On Thu, Sep 3, 2015 at 10:30 AM, Usman Ehtesham Gul <
notifications@github.com> wrote:

> Update: yesterday i worked on integrating the hash ids and anonymize
> options for forum, course-completers and ip-to-country. The first two had
> no issues. But ip-to-country has a couple of issues:
> 1) there are alot of edge cases on the type of the username provided.
> Apart from a string it can be a number, a long number or a string can be
> converted into a number....trying to figure that out
> 2) Tracking collection has number of documents in the millions and number
> of documents in user_id_map is equal to the number of students
> (5000-30000). So anonymizing ip-to-country is going to take a long long
> time IF i use user_id_map to find the user_id and hash_id of given username
> from the tracking document. Alternate solution is to do the steps
> sequentially. First i generate an intermediate result from the tracking
> logs part and then I use the intermediate result to anonymize it and
> finally generate the report
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/McGillX/edx_data_research/issues/27#issuecomment-137466526>
> .
>



-- 

*Alexander Steeves-Fuentes* | Courseware Developer | McGillX

*Teaching and Learning Services* | McGill University | McLennan Library
Building, MS-12 | 3459 McTavish Street | Montreal, Quebec | H3A 0C8 |
http://www.mcgill.ca/tls

**Comment by ueg1990** [comment]
Intermediate results path made a big difference to performance (6-7 times); so for ip-to-country, i am keeping that approach.  For body101x:
Number of records: 56126
Number of unique users: 28115
Number of users with no name (default value set to 'unknown'): 25683
Issue with users with no name: No way of knowing if those are the same people for given country and/or ip address. I check for uniqueness by (user, country) because many different ips may map to same country. but bcuz of this all sets with user 'unknown', there will be lots of ('unknown', <name_of_country>) records without knowing if they are mapped to the same user or different user. 
And there were quite a few IPs that did not give a country. ill look into it further later. till then ill upload the report i got, and maybe u can have look and check if it looks right and if you observer any issues, let me know. 
But i would suggest disregard records where username is 'unknown' (thats the value is set for usernames which were empty strings)

**Comment by AlexanderFuentes** [comment]
The regards which are not associate with a username are for people who
aren't logged in so you can actually disregard those from the script.

Perhaps add in a print statement to the command line telling the user the
number of unknowns but you can leave it out of the CSV report if that
cleans things up.

**Comment by ueg1990** [comment]
There are two types of 'unknown' fields:
1) Usernames which are unknown and therefore the hash_id and user_id also have values 'unknown'
2) Usernames which are not unknown but they did not have a user_id and hash_id so the format is (username, 'unknown', 'unknown'
Which one should I remove? Based on that I can get a count of the number of unknowns
I am not really worried about the cleaning up; it s about what would you like to see in the output report for ip-to-country
