### ISSUE TITLE
Update tracking logs parsing script to insert hash_id and user_id

### ISSUE THREAD

**Issue by ueg1990** [McGillX/edx_data_research#29]
two possibilities:
1) include the hash_id and user_id directory from user_id_map
2) include a reference to the student_id_map by storing the ObjectId corresponding to the username in both tracking and user_id_map
both will result in a constraint that (just like the course_structure collection), the user_id_map collection needs to be parsed first
What do u think?
Aside: We can maybe even do it for all other collections, but then we will not be able to use the mongoimport commands...rather we will have to do this via python.

**Comment by AlexanderFuentes** [comment]
Either 1) or neither. At the moment when we create the problem ID
collections we add in the hash id so we can anonymise the output. The only
other instance of is with the user info script which currently access
multiple collections and always will unless we create a new user info
collection. But I don't see the utility given that it's a single report we
generate one time for a course.

Did I understand correctly.

Think we need to revisit the user info report and other basic/global one
time reports we generate for all courses.

Perhaps after setup having a series of command line prompts which guide the
user through generating all the basic reports.

There are a few reports we will always run on a course, some of which
require user input:

User info (combining a lot of information from certificates, profile data)

Country of origin by ip address. This could be combined with the user info
report. Have to figure out the best formatting in the case of users who
access from multiple countries.

Entrance and exit survey using the problem ID script which requires input
from the user (providing two or more problem ids)

The last output would be something we haven't done yet but it would be a
course info sheet providing general stats and demographics about the course.

**Comment by AlexanderFuentes** [comment]
I guess what I'm suggesting is a progression towards "one click" install,
setup and run.

If its straightforward then we can encourage other universities like
Dartmouth and Karolinska to run it.
