### ISSUE TITLE
Course Stats Sheet

### ISSUE THREAD

**Issue by AlexanderFuentes** [McGillX/edx_data_research#32]
Add command to create a general stats report for courses:

Age breakdown (table) –
Under 20
20-29
30-39
40-49
50-69
70+
 
Total registered - %male - %female
number students who accessed graded component
number students who earned a certificate
number of of discussion threads

**Comment by ueg1990** [comment]
will each of these be a separate command and report?

**Comment by AlexanderFuentes** [comment]
Ideally a single command

**Comment by ueg1990** [comment]
this was done a few days ago
