### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by sijpkes** [McGillX/edx_data_research#42]
Hi there, I'm the 'data czar' for NewcastleX. Can you give me some pointers on how to start up the web service on this reporting application?  I have managed to deploy it but am finding no docs here:

http://mcgillx-research-documentation.readthedocs.io/en/latest/rstfiles/moocx_report_generation.html

I'm just trying to assess whether this is the right tool for our purposes.

**Comment by sijpkes** [comment]
It's been two weeks. Any pointers on this? Or is this repo inactive? If so it should be marked as such.

**Comment by mel374** [comment]
Hi Paul,

I am no longer working at McGill. I forwarded your previous email to my colleagues, but it may have gotten lost. I have cc'd them in this reply.
Regards,
Melanie

________________________________

**Comment by sijpkes** [comment]
Thanks @mel374 , McGill has made contact and it seems this repo is in fact inactive.  Thanks for contacting them.
