### ISSUE TITLE
Add hash_id to problem_id output

### ISSUE THREAD

**Issue by AlexanderFuentes** [McGillX/edx_data_research#9]
Basically add in the username to hash_id as part of the base script

**Comment by ueg1990** [comment]
since we want hash_id as part of problem ids scripts, do you think we should update the problem_ids collections such that it includes the user_id and hash_id for each document?

**Comment by AlexanderFuentes** [comment]
In the long run, yah that's probably a good idea

On Wed, Aug 19, 2015 at 8:25 PM, Usman Ehtesham Gul <
notifications@github.com> wrote:

> since we want hash_id as part of problem ids scripts, do you think we
> should update the problem_ids collections such that it includes the user_id
> and hash_id for each document?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/McGillX/edx_data_research/issues/9#issuecomment-132835436>
> .
>



-- 

*Alexander Steeves-Fuentes* | Courseware Developer | McGillX

*Teaching and Learning Services* | McGill University | McLennan Library
Building, MS-12 | 3459 McTavish Street | Montreal, Quebec | H3A 0C8 |
http://www.mcgill.ca/tls

**Comment by ueg1990** [comment]
Hash ID column added as part of CSV report. Once problem_ids becomes part of CLI, will make hash_id as only user column part of an command line option
